name: Keklist
version: ${project.version}
main: de.hdg.keklist.Keklist
api-version: '1.21'
description: ${project.description}
authors: [ "jxnxsdev", "SageSphinx63920" ]
website: https://keklist.pages.dev
loader: de.hdg.keklist.KeklistLoader
contributors: [ "LPTP1" ]
default-perm: op

dependencies:
  server:
    floodgate:
      load: BEFORE
      required: false

    Plan:
      load: BEFORE
      required: false

    LuckPerms:
      load: BEFORE
      required: false
      join-classpath: true

    PlaceholderAPI:
      required: false
      
    Geyser-Spigot:
      load: BEFORE
      required: false

permissions:
  keklist.gui.use:
    description: Allows the player to use general the GUI
    default: false

  keklist.gui.settings:
    description: Allows the player to use the settings GUI
    default: false

  keklist.manage.reload:
    description: Allows the player to reload the plugin
    default: op

  keklist.manage.whitelist:
    description: Allows the player to manage the whitelist
    default: op

  keklist.manage.blacklist:
    description: Allows the player to manage the blacklist
    default: op

  keklist.blacklist.info:
    description: Allows the player to see the blacklist
    default: op

  keklist.blacklist.add:
    description: Allows the player to add entries to the blacklist
    default: op

  keklist.blacklist.remove:
    description: Allows the player to remove entries from the blacklist
    default: op

  keklist.blacklist.motd:
    description: Allows the player to add entries the motd blacklist
    default: op

  keklist.whitelist.info:
    description: Allows the player to see the whitelist
    default: op

  keklist.whitelist.add:
    description: Allows the player to add entries to the whitelist
    default: op

  keklist.whitelist.remove:
    description: Allows the player to remove entries from the whitelist
    default: op

  keklist.notify.blacklist:
    description: Allows the player to see blacklist notifications
    default: false

  keklist.notify.whitelist:
    description: Allows the player to see whitelist notifications
    default: false

  keklist.notify.ip:
    description: Allows the player to see ip notifications on player join
    default: false

  keklist.info.use:
    description: Allows the player to use the info command
    default: op

  keklist.status.use:
    description: Allows the player to use the status command
    default: op